#!/usr/bin/env php
<?php
/**
 * File: otpgen
 * Author: Robin Rijkeboer <rmrijkeboer@gmail.com>
 */
include_once('vendor/autoload.php');

use beagon\OTPGen\OTPGen;

error_reporting(E_ALL);
ini_set('display_errors', 1);
$application = include dirname(__FILE__) . '/application.php';
$application->run();
